name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: Install OS Dependencies
        run: sudo apt-get update

      - name: npm run build
        run: npm run build

      - name: npm run test
        run: npm run test


